name: project ci/cd flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    # List the repository contents to verify its structure
    - name: List repository contents
      run: ls -l

    # Navigate to the directory where your Maven project resides
    - name: Navigate to project directory
      run: cd techhub || true  # Change to your actual directory name if different

    # List the contents of the directory to verify if it exists
    - name: List project directory contents
      run: ls -l

    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: kamil0304/springboot-images-new
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
